# -*- coding: utf-8 -*-
"""Assignment 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sVspw0KPBNGHQcLAGNpWGnxjtozFQFq0
"""

# Question 4
def celsius_to_fahrenheit(celsius):
    fahrenheit = celsius*(9/5) + 32
    return fahrenheit

celsius = float(input("Enter temperature in Celsius: "))
fahrenheit = celsius_to_fahrenheit(celsius)
print(f"{fahrenheit:.1f}")
