# -*- coding: utf-8 -*-
"""Assignment 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sVspw0KPBNGHQcLAGNpWGnxjtozFQFq0
"""

# Question  1
number_of_minutes = int(input("Enter number of minutes: "))
hours = number_of_minutes // 60
minutes = number_of_minutes % 60
print(f"{number_of_minutes} minutes is {hours} hour and {minutes} minutes.")

# Question 2
name = input("Please enter your first name: ")
print(f"Hello {name} and welcome to CS Online!")

# Question 3
quarters = int(input("Enter number of quarters: "))
dimes = int(input("Enter number of dimes: "))
nickels = int(input("Enter number of nickels: "))
pennies = int(input("Enter number of pennies: "))

total_cents = quarters*25 + dimes*10 + nickels*5 + pennies
total_dollars = total_cents / 100
print(f"Amount: ${total_dollars:.2f}")

# Question 4
def celsius_to_fahrenheit(celsius):
    fahrenheit = celsius*(9/5) + 32
    return fahrenheit

celsius = float(input("Enter temperature in Celsius: "))
fahrenheit = celsius_to_fahrenheit(celsius)
print(f"{fahrenheit:.1f}")

# Question 5
def number_square(number):
    square = number**2
    print(square)

number = int(input("Enter a number: "))
number_square(number)